name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Generate coverage reports
      run: ./gradlew aggregateJacocoReport
    - name: Add coverage to PR
      id: jacoco
      continue-on-error: true
      uses: madrapps/jacoco-report@v1.1
      with:
        path: ${{ github.workspace }}/build/reports/jacoco/aggregate/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        files: ${{ github.workspace }}/build/reports/jacoco/aggregate/jacocoTestReport.xml